base_url = "https://annefou.github.io"
compile_sass = true
title = "Anne Fouilloux"
description = "My personal website"
generate_feed = true
build_search_index = true
taxonomies = [
  { name = "tags", feed = true },
]

[markdown]
highlight_code = true
highlight_theme = "OneHalfLight"

[extra]
first_name = "Anne"
last_name = "Fouilloux"
address = "Oslo, Norway"
email = "annef-at-simula.no"
favicon = "/favicon.ico"
avatar = "/media/avatar.png"

katex = false
show_about = true
show_skills = true
show_projects = true
show_opensource = false
show_publications = false
show_experience = true
show_education = true
show_blog = false
